[phases.setup]
nixPkgs = ["bun", "nodejs_20"]

[phases.install]
cmds = [
  "cd apps/server && bun install",
  "cd apps/client && bun install && bun run build"
]

[start]
cmd = "bun apps/server/src/index.ts"
